### PR TITLE
fix: support the output package and development of ladle on Windows 

### LINKED ISSUE #67: Windows 11: Weird path resolving issue
Decided to give ladle a try on a new project. It worked fine until I tried to add a .ladle/ dir for some config bits. Below is the result of running `yarn ladle serve`. Notice in particular that the config.mjs isn't detected, and the path `.............ladleconfig.mjs` seems out of nowhere. Running on Windows 11, if that makes a difference.

```
➜ node -v
v16.13.2

➜ ls .ladle

    Directory: C:\dev123\packages\frontend\.ladle

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           3/22/2022  5:02 PM            203 components.tsx
-a---           3/22/2022  5:08 PM             53 config.mjs

➜ cat .ladle/config.mjs 
export default {
        "serve":{
                "port": 6000
        }
}

➜ yarn dev:ladle
yarn run v1.22.17
$ cross-env DEBUG=ladle* ladle serve .
  ladle:cli Starting serve command +0ms
  ladle:cli CLI theme: undefined +1ms
  ladle:cli CLI stories: undefined +0ms
  ladle:cli CLI port: undefined +0ms
  ladle:cli CLI open: undefined +0ms
  ladle:cli No custom config found. +1ms
  ladle:cli Final config:
  ladle:cli {
  ladle:cli   "stories": "src/**/*.stories.{js,jsx,ts,tsx}",
  ladle:cli   "root": "C:\\dev123\\packages\\frontend",
  ladle:cli   "defaultStory": "",
  ladle:cli   "babelPresets": [],
  ladle:cli   "babelPlugins": [],
  ladle:cli   "define": {},
  ladle:cli   "envPrefix": "VITE_",
  ladle:cli   "resolve": {
  ladle:cli     "alias": {}
  ladle:cli   },
  ladle:cli   "optimizeDeps": {
  ladle:cli     "include": []
  ladle:cli   },
  ladle:cli   "addons": {
  ladle:cli     "control": {
  ladle:cli       "enabled": true,
  ladle:cli       "defaultState": {}
  ladle:cli     },
  ladle:cli     "theme": {
  ladle:cli       "enabled": true,
  ladle:cli       "defaultState": "light"
  ladle:cli     },
  ladle:cli     "mode": {
  ladle:cli       "enabled": true,
  ladle:cli       "defaultState": "full"
  ladle:cli     },
  ladle:cli     "rtl": {
  ladle:cli       "enabled": true,
  ladle:cli       "defaultState": false
  ladle:cli     },
  ladle:cli     "ladle": {
  ladle:cli       "enabled": true
  ladle:cli     }
  ladle:cli   },
  ladle:cli   "serve": {
  ladle:cli     "open": "**Default**",
  ladle:cli     "port": 61000,
  ladle:cli     "define": {}
  ladle:cli   },
  ladle:cli   "build": {
  ladle:cli     "out": "build",
  ladle:cli     "sourcemap": false,
  ladle:cli     "baseUrl": "/",
  ladle:cli     "define": {}
  ladle:cli   }
  ladle:cli } +0ms
  ladle:cli Port set to: 61000 +5ms

   ╭───────────────────────────────────────────────────╮
   │                                                   │
   │   🥄 Ladle.dev served at http://localhost:61000   │
   │                                                   │
   ╰───────────────────────────────────────────────────╯

  ladle:vite transforming: C:/dev123/packages/frontend/node_modules/@ladle/react/lib/app/generated/generated-list.tsx +0ms
  ladle:vite Initial generation of the list +0ms
  ladle:vite Parsing src/app/components/UserIcon/UserIcon.stories.tsx +0ms
  ladle:vite Parsed data for src/app/components/UserIcon/UserIcon.stories.tsx: +61ms
  ladle:vite {
  ladle:vite   entry: 'src/app/components/UserIcon/UserIcon.stories.tsx',
  ladle:vite   stories: [
  ladle:vite     {
  ladle:vite       storyId: 'user-icon--default',
  ladle:vite       componentName: 'user$icon$$default',
  ladle:vite       namedExport: 'Default',
  ladle:vite       locStart: 3,
  ladle:vite       locEnd: 3
  ladle:vite     }
  ladle:vite   ],
  ladle:vite   exportDefaultProps: { title: undefined, meta: undefined },
  ladle:vite   namedExportToMeta: {},
  ladle:vite   namedExportToStoryName: {},
  ladle:vite   storyParams: {},
  ladle:vite   fileId: 'UserIcon'
  ladle:vite } +1ms
  ladle:vite C:\dev123\packages\frontend\.ladle/components.tsx found. +0ms
  ladle:vite Custom provider found. +1ms
Failed to resolve import ".............ladleconfig.mjs" from "node_modules\@ladle\react\lib\app\generated\generated-list.tsx". Does the file exist?
Failed to resolve import ".............ladleconfig.mjs" from "node_modules\@ladle\react\lib\app\generated\generated-list.tsx". Does the file exist? (x2)     
5:22:52 PM [vite] Internal server error: Failed to resolve import ".............ladleconfig.mjs" from "node_modules\@ladle\react\lib\app\generated\generated-list.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/dev123/packages/frontend/node_modules/@ladle/react/lib/app/generated/generated-list.tsx
  6  |  export let stories = { "user-icon--default": { component: user$icon$$default } };
  7  |  export let config = {};
  8  |  import customConfig from ".............ladleconfig.mjs";
     |                            ^
  9  |  config = customConfig;
  10 |  import { Provider as CustomProvider } from ".............ladlecomponents.tsx";
      at formatError (C:\dev123\packages\frontend\node_modules\@ladle\react\node_modules\vite\dist\node\chunks\dep-5a245411.js:36027:46)
      at TransformContext.error (C:\dev123\packages\frontend\node_modules\@ladle\react\node_modules\vite\dist\node\chunks\dep-5a245411.js:36023:19)
      at normalizeUrl (C:\dev123\packages\frontend\node_modules\@ladle\react\node_modules\vite\dist\node\chunks\dep-5a245411.js:56731:26)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (C:\dev123\packages\frontend\node_modules\@ladle\react\node_modules\vite\dist\node\chunks\dep-5a245411.js:56880:57)
      at async Object.transform (C:\dev123\packages\frontend\node_modules\@ladle\react\node_modules\vite\dist\node\chunks\dep-5a245411.js:36262:30)
      at async doTransform (C:\dev123\packages\frontend\node_modules\@ladle\react\node_modules\vite\dist\node\chunks\dep-5a245411.js:52681:29)
Failed to resolve import ".............ladleconfig.mjs" from "node_modules\@ladle\react\lib\app\generated\generated-list.tsx". Does the file exist?
```

### PR DESCRIPTION
**Pull request by talshani**
A complete fix including CI flow and upgrading playwright in order to make development and usage of the built package on windows

fixes #67

### CODE REVIEW

**Comment by talshani** [comment]
The entire build and test flow (lerna/npm scripts...) is still not fully cross-platform, but I have most of it ready.
I agree that this must be e2e tested using github actions, and it is still in progress,
but I just wanted to make this draft PR to have an early feedback...

most of the commits in this [branch](https://github.com/talshani/ladle/tree/windows-support), meant to fix the package.json and other build/test pipelines to make it cross-platform, still trying out different things to have the least impact on current workflow

Looking for ways to improve this...

File: packages/ladle/lib/cli/vite-plugin/generate/cleanup-windows-path.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+/**
+ * @param {string} path
+ * @return {string}
+ */
+function cleanupWindowsPath(path) {
+  return path.replace(/\\/g, "/");
```
Comment (wojtekmaj) [inline packages/ladle/lib/cli/vite-plugin/generate/cleanup-windows-path.js:6]: That reverses slashes though, maybe something like this?

```suggestion
  return path.replace(/\\/g, "\\\\");
```

Comment (beforan) [reply packages/ladle/lib/cli/vite-plugin/generate/cleanup-windows-path.js:6]: doesn't `/` work everywhere in Windows these days (NT6+)?

I always use it in powershell and node scripts and stuff.

I also checked `cmd.exe` and it had no issues with:
- `cd "Documents/My Web Sites/"`
- running an executable: `C:\>"Program Files (x86)/Steam/steamapps/common/Crusader Kings III/binaries/ck3.exe"`

It would seem that, while under the hood it still uses `\` as it's canonical directory path separator, [Windows converts `/` at the Windows API level](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#path-normalization), lower than anything in userspace.

Comment (talshani) [reply packages/ladle/lib/cli/vite-plugin/generate/cleanup-windows-path.js:6]: @wojtekmaj I think your suggestion can also work, but I think generating the same code independent of the OS is better in this case no?

Otherwise you risk more problems down the road, how the generated code is used.

`/` is supported in windows as imports in typescript.

**Comment by talshani** [comment]
I had some time off, and just got back to this PR, but I still struggle with making the CI flow work on windows:
https://github.com/talshani/ladle/tree/windows-support 

I think you can see the github actions if someone wants to take a look and see what's wrong, I had several tests there

Currently I think it is a problem in playwright and es module importing again on windows...

File: packages/ladle/lib/cli/vite-plugin/generate/cleanup-windows-path.js (hunk 1 above)
Comment (wojtekmaj) [reply packages/ladle/lib/cli/vite-plugin/generate/cleanup-windows-path.js:6]: Yeah, you're both right, I was being probably a bit too conservative with this one.

**Comment by tajo** [comment]
This is a great work. Thanks!

**Comment by cpakken** [comment]
Vite already has this issue and solution documented.

https://vitejs.dev/guide/api-plugin.html#path-normalization

Vite path (moduleId's) should be normalized with its included function

```js
import { normalizePath } from 'vite'

normalizePath('foo\\bar') // 'foo/bar'
normalizePath('foo/bar') // 'foo/bar'
```
Seems like it performs the same thing as your  `cleanupWindowsPath` function

**Comment by e-krebs** [comment]
the current solution has weird path issue resolution: it tries to resolve node package in the project folder.

(I had to add an alias workaround in my config, [cf. here](https://github.com/e-krebs/react-library/blob/main/vite.config.js))

what @cpakken is mentioning would probably resolve this issue
